rate: 40
# output
outputTopic: /robot/pwm
lpwm: 0
rpwm: 1
# todo we need to handle zero somehow
minPwm: 0
maxPwm: 4096
# base motor has 3.14160 rad/s at 255 pwm
minVelocity: 0.0
maxVelocity: 1.0
# input
inputTopic: /robot/adc
input: 0
# control
controlTopic: /arm_velocity_controller/follow_joint_trajectory/goal
joint: base
# base: 522 middle, 293 right, 790 left
minReading: 0
maxReading: 1023
minPos: 0
maxPos: 1
threshold: 8
average: 16
log: /home/val/catkin_ws/response.csv