rate: 50
# output
outputTopic: /pwm
lpwm: 0
rpwm: 1
minPwm: 64
maxPwm: 255
minVelocity: 0.0
maxVelocity: 1.0
# input
inputTopic: /adc
input: 0
minReading: 270
maxReading: 794
minPos: -1.4929
maxPos: 1.4929
threshold: 8
average: 8
# control
trajectoryTopic: /arm_velocity_controller/follow_joint_trajectory/goal
joint: base
# tune
feedbackTopic: /tune/feedback
commandTopic: /tune/command
tolerance: 0.05
pid:
  p: 0.8678
  i: 0.0119
  d: 0.0
  i_clamp: 1.0
  antiwindup: false