rate: 50
# output
outputTopic: /pwm
lpwm: 0
rpwm: 1
minPwm: 64
maxPwm: 255
minVelocity: 0.0
maxVelocity: 1.0
# input
inputTopic: /adc
input: 0
minReading: 330
maxReading: 100
minPos: -1.4929
maxPos: 1.4929
threshold: 8
average: 2
# control
trajectoryTopic: /arm_velocity_controller/follow_joint_trajectory/goal
joint: base
# tune
feedbackTopic: /tune/feedback
commandTopic: /tune/command
tolerance: 0.02
pid:
  p: -0.4079
  i: -0.05242
  d: -0.1964
  i_clamp: 1.0
  antiwindup: false