rate: 50
# output
outputTopic: /pwm
lpwm: 0
rpwm: 1
minPwm: 200
maxPwm: 255
minVelocity: 0.0
maxVelocity: 1.0
# input
inputTopic: /adc
input: 0
minReading: 976
maxReading: 848
minPos: -0.0508
maxPos: 0
threshold: 8
average: 8
# control
trajectoryTopic: /arm_velocity_controller/follow_joint_trajectory/goal
joint: forearm_actuator
# tune
feedbackTopic: /tune/feedback
commandTopic: /tune/command
tolerance: 0.0009
pid:
  p: 31.12
  i: 10.22
  d: 0.3102
  i_clamp: 1.0
  antiwindup: false