rate: 50
# output
outputTopic: /pwm
lpwm: 0
rpwm: 1
minPwm: 32
maxPwm: 255
minVelocity: 0.0
maxVelocity: 1.0
# input
inputTopic: /adc
input: 0
minReading: 185
maxReading: 140
minPos: 0.404676
maxPos: 0.813453
threshold: 8
average: 8
# control
trajectoryTopic: /gazebo/arm_velocity_controller/follow_joint_trajectory/goal
joint: upperarm_actuator
# tune
feedbackTopic: /tune/feedback
commandTopic: /tune/command
tolerance: 0.05
pid:
  p: 0.8678
  i: 0.0119
  d: 0.0
  i_clamp: 1.0
  antiwindup: false