rate: 50
# output
outputTopic: /pwm
lpwm: 0
rpwm: 1
minPwm: 32
maxPwm: 255
minVelocity: 0.0
maxVelocity: 1.0
# input
inputTopic: /adc
input: 0
minReading: 857
maxReading: 902
# need to set this to joint limits
minPos: 0
maxPos: 1
threshold: 8
average: 2
# control
trajectoryTopic: /arm_velocity_controller/follow_joint_trajectory/goal
joint: upperarm_actuator
# tune
feedbackTopic: /tune/feedback
commandTopic: /tune/command
tolerance: 0.05
pid:
  p: 3.149
  i: 4.687
  d: 0.03102
  i_clamp: 1.0
  antiwindup: false