rate: 50
# output
trajectoryTopic: /move_group/goal
outputTopic: /pwm
lpwm: 1
rpwm: 0
minPwm: 64
maxPwm: 255
minVelocity: 0.0
maxVelocity: 1.0
# input
inputTopic: /adc
input: 0
minReading: 283
maxReading: 771
minPos: -1.5708
maxPos: 1.5708
threshold: 8
average: 2
# control
joint: base
# tune
feedbackTopic: /tune/feedback
commandTopic: /tune/command
goalTopic: /move_group/goal
tolerance: 0.02
time: 1.0
pid:
  p: 0.4079
  i: 0.05242
  d: 0.1964
  i_clamp: 1.0
  antiwindup: false