rate: 40
# output
outputTopic: /robot/pwm
lpwm: 0
rpwm: 1
minPwm: 520
maxPwm: 4096
minVelocity: 0.0
maxVelocity: 1.0
# input
inputTopic: /robot/adc
input: 0
minReading: 293
maxReading: 790
minPos: -1.4929
maxPos: 1.4929
threshold: 8
average: 16
# control
trajectoryTopic: /arm_velocity_controller/follow_joint_trajectory/goal
commandTopic: /tune/command
joint: base
# recording
log: /home/val/catkin_ws/response.csv